apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  labels:
    app.kubernetes.io/name: blackbox-exporter
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 10s
        http:
          preferred_ip_protocol: "ip4"
          tls_config:
            insecure_skip_verify: true
      http_3xx:
        prober: http
        timeout: 10s
        http:
          preferred_ip_protocol: "ip4"
          follow_redirects: false
          tls_config:
            insecure_skip_verify: true
          valid_status_codes: [300, 301, 302, 303, 304, 305, 306, 307, 308]
      http_4xx:
        prober: http
        timeout: 10s
        http:
          preferred_ip_protocol: "ip4"
          follow_redirects: false
          tls_config:
            insecure_skip_verify: true
          valid_status_codes: [400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 421, 422, 423, 424, 425, 426, 428, 429, 431, 451, 418, 420, 444, 449, 499]
      tcp_connect:
        prober: tcp
